services:
  - type: web
    name: fileshare-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://fileshare-app-eight.vercel.app
    healthCheckPath: /api/health
